### ISSUE TITLE
It throws an error "Value '' at 'appArn' failed to satisfy constraint"

### ISSUE THREAD

**Issue by espekkaya** [realm/aws-devicefarm#8]
The following code throws an error as `Error: ValidationException: 2 validation errors detected: Value '' at 'appArn' failed to satisfy constraint: Member must satisfy regular expression pattern: ^arn:.+; Value '' at 'appArn' failed to satisfy constraint: Member must have length greater than or equal to 32`

But when I add `app_arn: ${{ secrets.AWS_PROJECT_ARN }}`, the error is gone. 

```
      - name: Schedule test run with mixed data
        uses: realm/aws-devicefarm/test-application@master
        id: schedule-run
        with:
          name: schedule-run
          project_arn: ${{ secrets.AWS_PROJECT_ARN }}
          app_arn: ${{ secrets.AWS_PROJECT_ARN }}
          device_pool_arn: ${{ secrets.AWS_DEVICE_POOL_ARN }}
          test_type: APPIUM_WEB_NODE
          test_package_file: ch-e2e-tests.zip
          test_package_type: APPIUM_WEB_NODE_TEST_PACKAGE
          test_spec_file: ./conf/aws/android-web.yml
          test_spec_type: APPIUM_WEB_NODE_TEST_SPEC
          file_artifacts: |
            Test spec file.yml
            Customer Artifacts.zip
          remote_src: true
```
